#!/bin/ksh
#
# install.sh -- OpenBSD guest setup for the privacy VM. Run as root right
# after the OpenBSD install:
#
#     doas ksh ./install.sh --mullvad ~/mullvad-configs.tgz --server se
#
# Order matters -- nothing is downloaded before Mullvad is up and tested:
#   1. internal-LAN NIC (MAC 08:00:27:77:00:01) -> 10.77.0.1/24, no IPv6
#   2. installs privctl, the rc.d script and /etc/hysteria templates (offline)
#   3. imports your Mullvad WireGuard configs, brings wg0 up with the chosen
#      server, routes all IPv4 through it, switches to Mullvad's DNS and checks
#      "You are connected to Mullvad" -- aborts if that fails
#   4. THROUGH MULLVAD: installs the official packages go + git (pkg_add, signed)
#   5. THROUGH MULLVAD: builds Hysteria 2 from the pinned release tag (commit
#      hash checked; Go checks every module against go.sum)
#
# It does NOT load a pf lock or start Hysteria. Routing alone already sends
# everything through wg0 (and fails rather than falling back if wg0 breaks);
# the pf kill switch is `privctl lock mullvad` + `privctl confirm`, run by you.
# Safe to rerun; existing config files are never overwritten.
#
# Options:
#   --mullvad SRC    your Mullvad configs: .tgz/.tar, a directory, or one .conf
#   --server NAME    server name or prefix (se, se-sto, de-fra-wg-001); default: random
#   --direct         allow installing WITHOUT Mullvad (not recommended)
#   --rebuild        rebuild Hysteria even if the pinned version is installed
#   --no-lan         do not touch network interface configuration

set -eu
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin
umask 022

HY_TAG="app/v2.12.3"                                     # upstream release tag
HY_VERSION="v2.12.3"
HY_COMMIT="e1366b173ccf5706e1e4630fe8aa654a4b574085"       # commit that tag points to
HY_REPO="https://github.com/apernet/hysteria.git"
HY_PKG="github.com/apernet/hysteria/app/v2/cmd"

LAN_MAC="08:00:27:77:00:01"
LAN_ADDR="10.77.0.1"
LAN_MASK="255.255.255.0"
MARK="generated by privctl"

KIT_DIR=$(cd "$(dirname "$0")" && pwd)
REBUILD=0; DO_LAN=1; DIRECT=0; MV_SRC=""; MV_SERVER=""
while [ $# -gt 0 ]; do
	case $1 in
	--mullvad) MV_SRC=${2:?--mullvad needs a path}; shift ;;
	--server) MV_SERVER=${2:?--server needs a name or prefix}; shift ;;
	--direct) DIRECT=1 ;;
	--rebuild) REBUILD=1 ;;
	--no-lan) DO_LAN=0 ;;
	*) echo "unknown option: $1" >&2; exit 2 ;;
	esac
	shift
done

step() { print -r -- "==> $*"; }
ok()   { print -r -- " ok  $*"; }
warn() { print -r -- "warn $*" >&2; }
die()  { print -r -- "FAIL $*" >&2; exit 1; }

# ------------------------------------------------------------------ checks
[ "$(uname -s)" = OpenBSD ] || die "run this inside the OpenBSD VM"
[ "$(id -u)" -eq 0 ] || die "run as root (doas ksh ./install.sh ...)"
[ "$(uname -m)" = amd64 ] || warn "tested for amd64; this is $(uname -m)"
case $(uname -r) in 7.9|8.*) ;; *) warn "written for OpenBSD 7.9; this is $(uname -r)" ;; esac
for f in privctl etc/privkit.conf etc/rc.d/hysteria etc/hysteria/config.yaml.template; do
	[ -f "$KIT_DIR/$f" ] || die "kit file missing: $KIT_DIR/$f (unzip the whole kit)"
done
mem=$(sysctl -n hw.physmem)
[ "$mem" -ge 1800000000 ] || warn "only $((mem / 1048576)) MB RAM; building Go code may fail below 2 GB"

# ------------------------------------------------------------------ 1. internal LAN
if [ $DO_LAN -eq 1 ]; then
	step "Internal LAN interface"
	lan=$(ifconfig | awk -v mac="$LAN_MAC" '
		/^[a-z]/ { ifn=$1; sub(/:$/, "", ifn) }
		$1 == "lladdr" && tolower($2) == mac { print ifn; exit }')
	if [ -z "$lan" ]; then
		warn "no NIC with MAC $LAN_MAC -- was the VM created by vbox-privacy-setup.sh? skipping LAN setup"
	elif [ -f "/etc/hostname.$lan" ] && ! grep -q "^inet $LAN_ADDR " "/etc/hostname.$lan"; then
		warn "/etc/hostname.$lan exists with other settings; leaving it alone. Wanted: inet $LAN_ADDR $LAN_MASK"
	else
		if [ ! -f "/etc/hostname.$lan" ]; then
			printf 'inet %s %s\n-inet6\nup\n' "$LAN_ADDR" "$LAN_MASK" >"/etc/hostname.$lan"
			chmod 640 "/etc/hostname.$lan"
		fi
		sh /etc/netstart "$lan"
		ok "$lan = $LAN_ADDR/24 (no IPv6), persistent via /etc/hostname.$lan"
	fi
fi

# ------------------------------------------------------------------ 2. files (offline)
step "Service user and files"
if ! id _hysteria >/dev/null 2>&1; then
	useradd -c "Hysteria 2 client" -d /var/empty -s /sbin/nologin -L daemon _hysteria
	ok "created user _hysteria"
fi
install -d -o root -g _hysteria -m 0750 /etc/hysteria
install -d -o root -g wheel -m 0755 /etc/hysteria/examples
install -d -o root -g wheel -m 0700 /var/db/privkit
install -o root -g bin -m 0555 "$KIT_DIR/privctl" /usr/local/sbin/privctl
install -o root -g bin -m 0555 "$KIT_DIR/etc/rc.d/hysteria" /etc/rc.d/hysteria
install -o root -g wheel -m 0644 "$KIT_DIR/etc/hysteria/config.yaml.template" /etc/hysteria/examples/config.yaml.template
install -o root -g wheel -m 0644 "$KIT_DIR/etc/privkit.conf" /etc/hysteria/examples/privkit.conf
if [ -f /etc/privkit.conf ]; then
	cmp -s "$KIT_DIR/etc/privkit.conf" /etc/privkit.conf || ok "kept your /etc/privkit.conf (kit version: /etc/hysteria/examples/privkit.conf)"
else
	install -o root -g wheel -m 0644 "$KIT_DIR/etc/privkit.conf" /etc/privkit.conf
fi
if [ ! -f /etc/hysteria/config.yaml ]; then
	install -o root -g _hysteria -m 0640 "$KIT_DIR/etc/hysteria/config.yaml.template" /etc/hysteria/config.yaml
	ok "created /etc/hysteria/config.yaml from the template (fill it in later)"
else
	chown root:_hysteria /etc/hysteria/config.yaml; chmod 0640 /etc/hysteria/config.yaml
	ok "kept existing /etc/hysteria/config.yaml"
fi
[ -f /var/db/privkit/mode ] || echo open >/var/db/privkit/mode
if [ ! -f /etc/doas.conf ]; then
	echo 'permit persist :wheel' >/etc/doas.conf; chmod 600 /etc/doas.conf
	ok "created /etc/doas.conf (members of group wheel may use doas)"
fi

# ------------------------------------------------------------------ 3. Mullvad first
step "Mullvad WireGuard -- every later download goes through it"
if [ -n "$MV_SRC" ]; then
	privctl mullvad import "$MV_SRC"
	if [ -n "$MV_SERVER" ] || ! grep -q "$MARK" /etc/hostname.wg0 2>/dev/null; then
		[ "$(cat /var/db/privkit/mode)" = open ] || die "a pf lock is on; run 'privctl unlock' first"
		# Empty prefix = random server from everything imported.
		privctl mullvad use "${MV_SERVER:-}"
	fi
fi
if grep -q "$MARK" /etc/hostname.wg0 2>/dev/null; then
	privctl mullvad test || die "Mullvad test failed -- nothing was downloaded. Try another server: privctl mullvad use <prefix>"
elif [ $DIRECT -eq 1 ]; then
	warn "--direct: installing WITHOUT Mullvad; package and source downloads show your real IP"
else
	die "no Mullvad config given. Use --mullvad <configs.tgz|dir|file.conf> [--server se], or --direct"
fi

# ------------------------------------------------------------------ 4. packages (through Mullvad)
step "Packages go + git (official OpenBSD packages)"
pkg_add -I go git
ok "$(go version | awk '{ print $3 }'), $(git --version)"

# ------------------------------------------------------------------ 5. build Hysteria (through Mullvad)
have=""
[ -x /usr/local/bin/hysteria ] && have=$(/usr/local/bin/hysteria version 2>/dev/null | awk '/^Version:/ { print $2 }')
if [ "$have" = "$HY_VERSION" ] && [ $REBUILD -eq 0 ]; then
	ok "hysteria $HY_VERSION already installed (use --rebuild to rebuild)"
else
	step "Building Hysteria $HY_VERSION from source (a few minutes)"
	build=""
	for d in /home /usr/local /var /tmp; do
		free=$(df -k "$d" | awk 'NR == 2 { print $4 }')
		if [ "${free:-0}" -ge 1500000 ]; then build="$d/hy2build"; break; fi
	done
	[ -n "$build" ] || die "need about 1.5 GB free in /home, /usr/local, /var or /tmp for the Go build"
	rm -rf "$build"; mkdir -p "$build/tmp"
	git -c advice.detachedHead=false clone --quiet --depth 1 --branch "$HY_TAG" "$HY_REPO" "$build/src"
	got=$(git -C "$build/src" rev-parse HEAD)
	[ "$got" = "$HY_COMMIT" ] || die "tag $HY_TAG resolves to $got, expected $HY_COMMIT -- refusing to build"
	ok "source commit verified: $got"
	ulimit -d "$(ulimit -H -d)" 2>/dev/null || true
	(
		cd "$build/src/app"
		export GOTOOLCHAIN=local GOFLAGS=-mod=readonly CGO_ENABLED=0
		export GOPATH="$build/gopath" GOCACHE="$build/gocache" GOTMPDIR="$build/tmp"
		go build -trimpath -o "$build/hysteria" -ldflags "-s -w \
			-X $HY_PKG.appVersion=$HY_VERSION -X $HY_PKG.appCommit=$HY_COMMIT \
			-X $HY_PKG.appDate=$(date -u +%Y-%m-%dT%H:%M:%SZ) -X $HY_PKG.appType=release \
			-X $HY_PKG.appPlatform=openbsd -X $HY_PKG.appArch=$(uname -m)" .
	)
	install -o root -g bin -m 0555 "$build/hysteria" /usr/local/bin/hysteria
	rm -rf "$build"
	ok "installed /usr/local/bin/hysteria ($(/usr/local/bin/hysteria version 2>/dev/null | awk '/^Version:/ { print $2 }'))"
fi

cat <<'EOF'

Done. No pf lock is loaded and Hysteria is not running.
Next (details in README.md):
  1. doas privctl status
  2. Mullvad kill switch:  doas privctl lock mullvad
     -> prove admin access from a NEW ssh session -> doas privctl confirm
     -> doas privctl persist            (keep it across reboots)
  3. Later, Hysteria: fill /etc/hysteria/config.yaml, then
     doas privctl hy2 start && doas privctl hy2 test
     doas privctl unlock && doas privctl lock tunnel && doas privctl confirm
  Emergency (VirtualBox console or ssh):  doas privctl unlock
EOF
